@base_url = http://localhost:5178

### Atualizar Serviço
PUT {{base_url}}/servicos/1
Content-Type: application/json

{
    "nome": "Doação de sangue",
    "descricao": "Doação de sangue para o hospital"
}

### Deletar Serviço
DELETE {{base_url}}/servicos/1
Content-Type: application/json
