@base_url = http://localhost:5178

### Cadastrar cuidador
POST {{base_url}}/cuidadores
Content-Type: application/json

{
    "nome": "Renan Santos",
    "email": "renanrls97@gmail.com",
    "cpfCnpj": "09173185957",
    "telefone": "41 99542-6236",
    "endereco": "Rua Mal. José Bernardino Bormann, 1346",   
    "dataNascimento": "1997-02-19"
}

### Listar cuidadores
GET {{base_url}}/cuidadores

### Buscar cuidador por id
GET {{base_url}}/cuidadores/1


### Cadastrar animal para cuidador
POST {{base_url}}/cuidadores/1/animal
Content-Type: application/json

{
    "nome": "Bolinha",
    "tipo": 1,
    "dataNascimento": "2024-02-19",
    "raca": "Vira-lata",
    "porte": "Pequeno",
    "peso": "5.5",
    "sexo": "Macho",
    "observacao": "Animal muito dócil"
}

