### Cadastrar Serviços
POST http://localhost:5178/servicos/cadastrar
Content-Type: application/json


{
    "nome": "Banho novo 3",
    "descricao": "Teste"
    
}

### Listar Serviços
GET http://localhost:5178/servicos/listar


### Buscar Serviço por ID

GET http://localhost:5178/servicos/buscar/3


### Deletar Serviço por ID

DELETE http://localhost:5178/servicos/deletar/3

### Atualizar Serviço por ID

PUT http://localhost:5178/servicos/atualizar/1
Content-Type: application/json

{
    "nome" : "Banho Alterado",
    "descricao" : "Banho Simples Alterado"
    
}
